### PR TITLE
Coarser grained tasks for forked SBT mode, fixing failure reporting

### LINKED ISSUE #185: Test report is wrong when `fork in Test := true`
Following test unexpectedly succeeds when `fork in Test := true`.

``` scala
import org.scalacheck.Properties
object Spec1 extends Properties("Spec1") {
  property("prop 1") = false
  property("prop 2") = true
}
```

```
[info] ! Spec1.prop 1: Falsified after 0 passed tests.
[info] + Spec1.prop 2: OK, proved property.
[info] Passed: Total 0, Failed 0, Errors 0, Passed 0
[success] Total time: 4 s, completed Jul 21, 2015 10:45:18 PM
```

I confirmed this issue was introduced by 82042613eebbde3c822328cbfab3c4186828f1f1 using `git bisect`.

Tested by sbt 0.13.8 and scalacheck 1.12.4.

### PR DESCRIPTION
**Pull request by retronym**
Fixes #185

Tested manually in the Scala build:

```
[success] Total time: 4 s, completed 13/03/2018 1:12:27 PM
> scalacheck/testOnly TreeMapTest
[info] Compiling 1 Scala source to /Users/jz/code/scala/target/scalacheck/test-classes...
[info] + TreeMap.foreach/iterator consistency: OK, passed 100 tests.
[info] + TreeMap.worst-case tree height is iterable: OK, passed 100 tests.
[info] + TreeMap.sorted: OK, passed 100 tests.
[info] + TreeMap.contains all: OK, passed 100 tests.
[info] + TreeMap.size: OK, passed 100 tests.
[info] + TreeMap.toSeq: OK, passed 100 tests.
[info] + TreeMap.head: OK, passed 100 tests.
[info] + TreeMap.last: OK, passed 100 tests.
[info] + TreeMap.head/tail identity: OK, passed 100 tests.
[info] + TreeMap.init/last identity: OK, passed 100 tests.
[info] + TreeMap.take: OK, passed 100 tests.
[info] + TreeMap.drop: OK, passed 100 tests.
[info] + TreeMap.take/drop identity: OK, passed 100 tests.
[info] + TreeMap.splitAt: OK, passed 100 tests.
[info] + TreeMap.slice: OK, passed 100 tests.
[info] + TreeMap.takeWhile: OK, passed 100 tests.
[info] + TreeMap.dropWhile: OK, passed 100 tests.
[info] + TreeMap.span identity: OK, passed 100 tests.
[info] + TreeMap.from is inclusive: OK, passed 100 tests.
[info] + TreeMap.to is inclusive: OK, passed 100 tests.
[info] ! TreeMap.faily: Falsified after 1 passed tests.
[info] > ARG_0: 0
[info] > ARG_0_ORIGINAL: -1814962128
[info] + TreeMap.until is exclusive: OK, passed 100 tests.
[info] + TreeMap.remove single: OK, passed 100 tests.
[info] + TreeMap.remove all: OK, passed 100 tests.
[error] Failed: Total 24, Failed 1, Errors 0, Passed 23
[error] Failed tests:
[error]     TreeMapTest
[error] (scalacheck/test:testOnly) sbt.TestsFailedException: Tests unsuccessful
[error] Total time: 4 s, completed 13/03/2018 1:12:35 PM
```

Previously:

```
> scalacheck/testOnly TreeMapTest
Picked up _JAVA_OPTIONS: -Xdebug -Xrunjdwp:transport=dt_socket,server=y,suspend=y,address=5006
Listening for transport dt_socket at address: 5006
[info] + TreeMap.splitAt: OK, passed 100 tests.
[info] + TreeMap.init/last identity: OK, passed 100 tests.
[info] ! TreeMap.faily: Falsified after 1 passed tests.
[info] > ARG_0: 0
[info] + TreeMap.span identity: OK, passed 100 tests.
[info] + TreeMap.remove all: OK, passed 100 tests.
[info] + TreeMap.contains all: OK, passed 100 tests.
[info] + TreeMap.takeWhile: OK, passed 100 tests.
[info] + TreeMap.until is exclusive: OK, passed 100 tests.
[info] + TreeMap.dropWhile: OK, passed 100 tests.
[info] + TreeMap.drop: OK, passed 100 tests.
[info] + TreeMap.take: OK, passed 100 tests.
[info] + TreeMap.worst-case tree height is iterable: OK, passed 100 tests.
[info] + TreeMap.foreach/iterator consistency: OK, passed 100 tests.
[info] + TreeMap.sorted: OK, passed 100 tests.
[info] + TreeMap.from is inclusive: OK, passed 100 tests.
[info] + TreeMap.to is inclusive: OK, passed 100 tests.
[info] + TreeMap.head: OK, passed 100 tests.
[info] + TreeMap.remove single: OK, passed 100 tests.
[info] + TreeMap.slice: OK, passed 100 tests.
[info] + TreeMap.size: OK, passed 100 tests.
[info] + TreeMap.last: OK, passed 100 tests.
[info] + TreeMap.head/tail identity: OK, passed 100 tests.
[info] + TreeMap.toSeq: OK, passed 100 tests.
[info] + TreeMap.take/drop identity: OK, passed 100 tests.
[info] Passed: Total 1, Failed 0, Errors 0, Passed 1
[success] Total time: 5 s, completed 13/03/2018 10:13:31 AM
```

### CODE REVIEW

File: src/main/scala/org/scalacheck/ScalaCheckFramework.scala [hunk 1]
```diff
@@ -34,13 +34,19 @@ private abstract class ScalaCheckRunner extends Runner {
...
-    else checkPropTask(taskDef)
+    else checkPropTask(taskDef, single = true)
   }
 
   def serializeTask(task: Task, serializer: TaskDef => String) =
     serializer(task.taskDef)
 
-  def tasks(taskDefs: Array[TaskDef]): Array[Task] = taskDefs.map(rootTask)
+  def tasks(taskDefs: Array[TaskDef]): Array[Task] = {
+    val isForked = taskDefs.exists(_.fingerprint().getClass.getName.contains("ForkMain"))
```
Comment (retronym) [inline src/main/scala/org/scalacheck/ScalaCheckFramework.scala]: This is a bit icky, but I'm not aware of an official way to detect if we're forked or not. /cc @dwijnand @eed3si9n

**Comment by retronym** [comment]
I don't see an obvious way to update SBT to make things work without this change.

I first tried changing the server (that receives the events) to merge them:

```diff
⚡ git diff head
diff --git a/main/actions/src/main/scala/sbt/ForkTests.scala b/main/actions/src/main/scala/sbt/ForkTests.scala
index 4791a081b..a554f3b13 100644
--- a/main/actions/src/main/scala/sbt/ForkTests.scala
+++ b/main/actions/src/main/scala/sbt/ForkTests.scala
@@ -137,7 +137,12 @@ private final class React(is: ObjectInputStream, os: ObjectOutputStream, log: Lo
       val event = TestEvent(tEvents)
       listeners.foreach(_ testEvent event)
       val suiteResult = SuiteResult(tEvents)
-      results += group -> suiteResult
+      results.get(group) match {
+        case Some(sr: SuiteResult) => results(group) = sr + SuiteResult(tEvents)
+        case _ => results(group) = suiteResult
+      }
+      // Don't want to defer this until the end of the run! Maybe the underlying framework
+      // really needs to manage a buffer of these events until the group is complete.
       listeners.foreach(_ endGroup (group, suiteResult.result))
       react()
   }
```

But we end up calling `endGroup` more than once for a given `name` which is likely to mess up reporters.

So it seems the right place to fix this is in [`ForkMain`](https://github.com/sbt/sbt/blob/684e2c369269e2aded5861c06aaad6f0b6b70a30/testing/agent/src/main/java/sbt/ForkMain.java#L264-L283), which would be changed to have the same [task structure as non-forked tests](https://github.com/sbt/sbt/blob/54d54b9f4f03e2e3339373ed582f2b19359bea31/testing/src/main/scala/sbt/TestFramework.scala#L63-L93)

But I can't really understand why the non-forked version works, either. 😕

**Comment by retronym** [comment]
I've created a ticket for the SBT behaviour in https://github.com/sbt/sbt/issues/4010, which is based on a standalone reproduction using a toy test framework modelled after the structure used here in Scalacheck. I hope we can merge this workaround and get a new Scalacheck release out in the meantime.

**Comment by retronym** [comment]
ping @rickynils. While we've worked around this in our build by copy/pasting this PR into our tests, it would be good to get this into a release soon.
